### ISSUE TITLE
Python Module Import Error [3.1.3]

### ISSUE THREAD

**Issue by anthok** [sleuthkit/autopsy#1414] opened 2015-07-01 19:04 UTC
Python scripts can no longer contain "py" in the file name.
If there is a "py" in the file name, then it will give you the following error

Example:
Filename - detect_entropy.py

     Import Error:No module named detect_entr

Tested on 3.1.2 and 3.1.3
The error only exists on 3.1.3, it will work fine on 3.1.2

If the file name is changed to detect_entro.py then it works on 3.1.3

**Comment by kefir-** [comment] 2015-07-01 19:50
This is presumably caused by line 123 in Core/src/org/sleuthkit/autopsy/python/JythonModuleLoader.java:

    String moduleName = script.getName().replaceAll(".py", ""); //NON-NLS

It looks like replaceAll() takes regular expressions:

http://www.tutorialspoint.com/java/java_string_replaceall.htm

in which case ".py" also matches "opy". I think this was introduced in cc8120a6600b1d97b304b227eb369cbf4af5d9bf.

**Comment by anthok** [comment] 2015-07-01 20:00
String moduleName = script.getName().replaceAll("\.py", ""); //NON-NLS should escape it

**Comment by kefir-** [comment] 2015-07-01 21:10
That would still remove all occurrences of ".py". Something like this seems more accurate:

    String moduleName = script.getName();
    if (moduleName.endsWith(".py")) {
        moduleName = moduleName.substring(0, moduleName.length() - 3);
    }

**Comment by rcordovano** [comment] 2016-04-01 21:22
This issue was resolved in commit cb346a00fe51afb0493f7a7ec8a872204bb307d2 on July 15, 2015 with a suitable regex:

{code}
String moduleName = script.getName().replaceAll("\\.py$", "");
{code}

**Closed by rcordovano** 2016-04-01 21:22 UTC
