### ISSUE TITLE
Web history not working well in Autopsy 4.21

### ISSUE THREAD

**Issue by phy-development** [sleuthkit/autopsy#7893] opened 2024-04-15 13:15 UTC
Hello,
I have recently upgraded from Autopsy 4.19 to Autopsy 4.21.
I am working with this disk image: http://perito.legal/traidor.img.zip
Mirror for the case the previous one doesn't work: https://drive.google.com/file/d/1yBLsxCjMcO6iV2lvMloI64CLUizQouJ0/view
(you must uncompress the file after downloading).

When I used Autopsy 4.19 and executed Recent Activity, I used to get 496 entries in Web History and 80 entries in web search as shown in this image.
![Autopsy4 19](https://github.com/sleuthkit/autopsy/assets/71018722/0e3d6fee-a5fe-48c8-82b3-d4784d39ea01)

However, when I execute the very same ingest module in Autopsy 4.21, I only get 201 entries in Web History and 44 in Web search, as shown in this picture:
![Autopsy 4 21](https://github.com/sleuthkit/autopsy/assets/71018722/6a5d386f-3216-4c1f-af0b-31198ec6a82e)

Especially, I noticed that am missing some navigations to flight companies in which the user tries to buy a flight, shown in the first picture. I know those searches and navigations should be there because I created the virtual machine and the forensic image.
Many of my students are experiencing the same problem.
Please help.
Best regards,
Phy

**Comment by markmckinnon** [comment] 2024-04-16 21:27
Thank you for providing a sample image to use to debug this issue.  You are correct that there is an issue and the problem is that the Opera Browser does not have any profiles and it is looking for profiles to determine where all the browsing history is.  I am working on a fix for this.

**Comment by markmckinnon** [comment] 2024-04-17 01:11
Fixed with PR https://github.com/sleuthkit/autopsy/pull/7895

**Comment by markmckinnon** [comment] 2024-04-18 14:14
PR is now merged in.  Closing this issue as resolved.  If this is still an issue in the future please create a new issue or reopen this issue.

**Closed as completed by markmckinnon** 2024-04-18 14:14 UTC
